export const AVAILABLE_SONGS = [
  {
    file: '0.mp3',
    name: 'Hamare Saath Shri Raghunath',
    artist: 'Sagar Kendurkar',
    color: '#393939',
    image: '1.jpg',
  },
  {
    file: '1.mp3',
    name: 'Superman',
    artist: 'Eminem',
    color: '#E91E63',
    image: '2.jpg',
  },
  {
    file: '2.mp3',
    name: 'Akuma No Ko',
    artist: 'Higuchi Ai',
    color: '#9c27b0',
    image: '3.jpg',
  },
  {
    file: '3.mp3',
    name: 'Ude jab jab zulfein',
    artist: 'Aasha Bhosle',
    color: '#795548',
    image: '4.jpeg',
  },
  {
    file: '4.mp3',
    name: 'Chitta Kurta',
    artist: 'Karan Aujla',
    color: '#9E9E9E',
    image: '5.jpg',
  },
  {
    file: '5.mp3',
    name: 'Closer',
    artist: 'The Chainsmokers',
    color: '#FF5722',
    image: '6.png',
  },
  {
    file: '6.mp3',
    name: 'Deva Deva',
    artist: 'Arijit Singh',
    color: '#0073ce',
    image: '7.jpg',
  },
  {
    file: '7.mp3',
    name: 'So High',
    artist: 'Sidhu Moosewala',
    color: '#0073ce',
    image: '8.jpg',
  },
  {
    file: '8.mp3',
    name: 'Ghost',
    artist: 'Justin Bieber',
    color: '#0073ce',
    image: '9.jpeg',
  },
  {
    file: '9.mp3',
    name: 'Shinonuga e-wa',
    artist: 'Fujii Kaze',
    color: '#0073ce',
    image: '10.jpeg',
  },
  {
    file: '10.mp3',
    name: 'Pink Lips',
    artist: 'Sunny Leone',
    color: '#0073ce',
    image: '11.jpg',
  }
] as const;
