export const AVAILABLE_SONGS = [

  {
    file: '1.mp3',
    name: 'Superman',
    artist: 'Eminem',
    color: '#75201D',
    image: '2.jpg',
  },
  {
    file: '0.mp3',
    name: 'Hamare Saath Shri Raghunath',
    artist: 'Sagar Kendurkar',
    color: '#F66F1A',
    image: '1.jpg',
  },
  {
    file: '2.mp3',
    name: 'Akuma No Ko',
    artist: 'Higuchi Ai',
    color: '#292B28',
    image: '3.jpg',
  },
  {
    file: '3.mp3',
    name: 'Ude jab jab zulfein',
    artist: 'Aasha Bhosle',
    color: '#402A13',
    image: '4.jpeg',
  },
  {
    file: '4.mp3',
    name: 'Chitta Kurta',
    artist: 'Karan Aujla',
    color: '#4B9FA2',
    image: '5.jpg',
  },
  {
    file: '5.mp3',
    name: 'Closer',
    artist: 'The Chainsmokers',
    color: '#D6D6CA',
    image: '6.png',
  },
  {
    file: '6.mp3',
    name: 'Deva Deva',
    artist: 'Arijit Singh',
    color: '#2C3C97',
    image: '7.jpg',
  },
  {
    file: '7.mp3',
    name: 'So High',
    artist: 'Sidhu Moosewala',
    color: '#ECE3D2',
    image: '8.jpg',
  },
  {
    file: '8.mp3',
    name: 'Ghost',
    artist: 'Justin Bieber',
    color: '#66C699',
    image: '9.jpeg',
  },
  {
    file: '9.mp3',
    name: 'Shinonuga e-wa',
    artist: 'Fujii Kaze',
    color: '#424242',
    image: '10.jpeg',
  },
  {
    file: '10.mp3',
    name: 'Pink Lips',
    artist: 'Sunny Leone',
    color: '#040404',
    image: '11.jpg',
  }
] as const;
