import { ReactOriginal, NodejsOriginal, JavascriptPlain, TypescriptOriginal, PostmanOriginal } from 'devicons-react';

import {
  SiD3Dotjs,
  SiEjs,
  SiFastapi,
  SiTensorflow,
  SiEthereum,
  SiPolygon,
  SiStreamlit,
  SiGraphql,
  SiPrisma,
  SiPython,
  SiScikitlearn,
  SiMlflow,
  SiPrometheus,
  SiGrafana,
} from 'react-icons/si';

import { FaDatabase } from 'react-icons/fa';

import { FaBrain } from 'react-icons/fa';  // For GenAI (using brain icon)
import { IoMdGitNetwork } from 'react-icons/io'; // Placeholder for WebSocket
import { GiFactory } from 'react-icons/gi'; // Placeholder for Apache Mahout

import {
  FaAws,
  FaBootstrap,
  FaDocker,
  FaGitlab,
  FaGithub,
  FaCss3Alt,
} from 'react-icons/fa';

import { FaGit, FaLinux } from 'react-icons/fa';
import { SiExpress, SiVite, SiMysql } from 'react-icons/si';

import {
  SiKubernetes,
  SiRedis,
  SiPostgresql,
  SiFirebase,
  SiMongodb,
  SiTailwindcss,
  SiStripe,
  SiJsonwebtokens,
  SiSocketdotio,
  SiRedux,
  SiRazorpay,
} from 'react-icons/si';

import { MdSpeed } from 'react-icons/md'; // Performance icon

export const tags = {
  React: {
    text: 'React.js',
    color: 'white',
    link: 'https://reactjs.org/',
    icon: <ReactOriginal />,
    image: 'https://upload.wikimedia.org/wikipedia/commons/a/a7/React-icon.svg',
  },
  'Node.js': {
    text: 'Node.js',
    color: 'white',
    link: 'https://nodejs.org/',
    icon: <NodejsOriginal />,
    image: 'https://upload.wikimedia.org/wikipedia/commons/d/d9/Node.js_logo.svg',
  },
  JavaScript: {
    text: 'JavaScript',
    color: 'white',
    link: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript',
    icon: <JavascriptPlain />,
    image: 'https://upload.wikimedia.org/wikipedia/commons/6/6a/JavaScript-logo.png',
  },
  TypeScript: {
    text: 'TypeScript',
    color: 'white',
    link: 'https://www.typescriptlang.org/',
    icon: <TypescriptOriginal />,
    image: 'https://upload.wikimedia.org/wikipedia/commons/4/4c/Typescript_logo_2020.svg',
  },
  Docker: {
    text: 'Docker',
    color: 'white',
    link: 'https://www.docker.com/',
    icon: <FaDocker />,
    image: 'https://www.docker.com/wp-content/uploads/2022/03/Moby-logo.png',
  },
  D3js: {
    text: 'D3.js',
    color: 'white',
    link: 'https://d3js.org/',
    icon: <SiD3Dotjs />,
    image: 'https://d3js.org/logo.svg',
  },
  EJS: {
    text: 'EJS',
    color: 'white',
    link: 'https://ejs.co/',
    icon: <SiEjs />,
    image: 'https://ejs.co/images/logo.svg',
  },
  Hadoop: {
    text: 'Apache Hadoop',
    color: 'white',
    link: 'https://hadoop.apache.org/',
    icon: <FaDatabase />,
    image: 'https://hadoop.apache.org/images/hadoop-logo.svg',
  },
  ApacheMahout: {
    text: 'Apache Mahout',
    color: 'white',
    link: 'https://mahout.apache.org/',
    icon: <GiFactory />,
    image: 'https://mahout.apache.org/images/mahout_logo.png',
  },
  FastAPI: {
    text: 'FastAPI',
    color: 'white',
    link: 'https://fastapi.tiangolo.com/',
    icon: <SiFastapi />,
    image: 'https://fastapi.tiangolo.com/img/logo-margin/logo-teal.png',
  },
  TensorFlow: {
    text: 'TensorFlow',
    color: 'white',
    link: 'https://www.tensorflow.org/',
    icon: <SiTensorflow />,
    image: 'https://www.tensorflow.org/images/tf_logo_social.png',
  },
  Ethereum: {
    text: 'Ethereum',
    color: 'white',
    link: 'https://ethereum.org/',
    icon: <SiEthereum />,
    image: 'https://ethereum.org/static/6a436922b38e650d74bb8238c33b8a52/6a435/eth-diamond-black.png',
  },
  Polygon: {
    text: 'Polygon',
    color: 'white',
    link: 'https://polygon.technology/',
    icon: <SiPolygon />,
    image: 'https://polygon.technology/media-kit/matic-token-icon.svg',
  },
  Streamlit: {
    text: 'Streamlit',
    color: 'white',
    link: 'https://streamlit.io/',
    icon: <SiStreamlit />,
    image: 'https://streamlit.io/images/brand/streamlit-logo-secondary-colormark-darktext.png',
  },
  GraphQL: {
    text: 'GraphQL',
    color: 'white',
    link: 'https://graphql.org/',
    icon: <SiGraphql />,
    image: 'https://graphql.org/img/logo.svg',
  },
  GenAI: {
    text: 'Generative AI',
    color: 'white',
    link: 'https://en.wikipedia.org/wiki/Generative_artificial_intelligence',
    icon: <FaBrain />,
    image: 'https://upload.wikimedia.org/wikipedia/commons/e/e9/Artificial_Intelligence_logo.svg',
  },
  PostgreSQL: {
    text: 'PostgreSQL',
    color: 'white',
    link: 'https://www.postgresql.org/',
    icon: <SiPostgresql />,
    image: 'https://upload.wikimedia.org/wikipedia/commons/2/29/Postgresql_elephant.svg',
  },
  Prisma: {
    text: 'Prisma',
    color: 'white',
    link: 'https://www.prisma.io/',
    icon: <SiPrisma />,
    image: 'https://www.prisma.io/images/brand/logo_dark.svg',
  },
  WebSocket: {
    text: 'WebSocket',
    color: 'white',
    link: 'https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API',
    icon: <IoMdGitNetwork />,
    image: 'https://upload.wikimedia.org/wikipedia/commons/6/66/WebSocket_Logo.svg',
  },
  Python: {
    text: 'Python',
    color: 'white',
    link: 'https://www.python.org/',
    icon: <SiPython />,
    image: 'https://www.python.org/static/community_logos/python-logo.png',
  },
  ScikitLearn: {
    text: 'Scikit-learn',
    color: 'white',
    link: 'https://scikit-learn.org/',
    icon: <SiScikitlearn />,
    image: 'https://scikit-learn.org/stable/_static/scikit-learn-logo-small.png',
  },
  MLflow: {
    text: 'MLflow',
    color: 'white',
    link: 'https://mlflow.org/',
    icon: <SiMlflow />,
    image: 'https://mlflow.org/docs/latest/_static/mlflow-logo.png',
  },
  Prometheus: {
    text: 'Prometheus',
    color: 'white',
    link: 'https://prometheus.io/',
    icon: <SiPrometheus />,
    image: 'https://prometheus.io/assets/prometheus_logo_grey.png',
  },
  Grafana: {
    text: 'Grafana',
    color: 'white',
    link: 'https://grafana.com/',
    icon: <SiGrafana />,
    image: 'https://grafana.com/static/img/grafana_icon.svg',
  },
  Postman: {
    text: 'Postman',
    color: 'white',
    link: 'https://www.postman.com/',
    icon: <PostmanOriginal />,
    image:
      'https://uxwing.com/wp-content/themes/uxwing/download/brands-and-social-media/postman-icon.png',
  },
  GitLab: {
    text: 'GitLab',
    color: 'white',
    link: 'https://gitlab.com/',
    icon: <FaGitlab />,
    image: 'https://about.gitlab.com/images/press/logo/png/gitlab-logo-gray-stacked-rgb.png',
  },
  GitHub: {
    text: 'GitHub',
    color: 'white',
    link: 'https://github.com/',
    icon: <FaGithub />,
    image: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png',
  },
  Bootstrap: {
    text: 'Bootstrap',
    color: 'white',
    link: 'https://getbootstrap.com/',
    icon: <FaBootstrap />,
    image: 'https://getbootstrap.com/docs/5.3/assets/brand/bootstrap-logo-shadow.png',
  },
  AWS: {
    text: 'AWS',
    color: 'white',
    link: 'https://aws.amazon.com/',
    icon: <FaAws />,
    image: 'https://a0.awsstatic.com/libra-css/images/logos/aws_logo_smile_1200x630.png',
  },
  'CI/CD': {
    text: 'CI/CD',
    color: 'white',
    link: 'https://en.wikipedia.org/wiki/CI/CD',
    icon: <FaGitlab />,
    image: 'https://cdn-icons-png.flaticon.com/512/3509/3509412.png',
  },
  Kubernetes: {
    text: 'Kubernetes',
    color: 'white',
    link: 'https://kubernetes.io/',
    icon: <SiKubernetes />,
    image: 'https://upload.wikimedia.org/wikipedia/commons/3/39/Kubernetes_logo_without_workmark.svg',
  },
  Redis: {
    text: 'Redis',
    color: 'white',
    link: 'https://redis.io/',
    icon: <SiRedis />,
    image: 'https://redis.io/images/redis-white.png',
  },
  Firebase: {
    text: 'Firebase',
    color: 'white',
    link: 'https://firebase.google.com/',
    icon: <SiFirebase />,
    image: 'https://firebase.google.com/downloads/brand-guidelines/PNG/logo-standard.png',
  },
  Mongo: {
    text: 'MongoDB',
    color: 'white',
    link: 'https://www.mongodb.com/',
    icon: <SiMongodb />,
    image: 'https://webassets.mongodb.com/_com_assets/cms/mongodb_logo1-76twgcu2dm.png',
  },
  Tailwindcss: {
    text: 'Tailwind CSS',
    color: 'white',
    link: 'https://tailwindcss.com/',
    icon: <SiTailwindcss />,
    image: 'https://upload.wikimedia.org/wikipedia/commons/d/d5/Tailwind_CSS_Logo.svg',
  },
  Performance: {
    text: 'Performance Optimization',
    color: 'white',
    link: 'https://web.dev/performance-scoring/',
    icon: <MdSpeed />,
    image: 'https://upload.wikimedia.org/wikipedia/commons/e/e8/Speedometer_icon.svg',
  },
  HTML: {
    text: 'HTML5',
    color: 'white',
    link: 'https://developer.mozilla.org/en-US/docs/Web/HTML',
    icon: <FaCss3Alt />,
    image: 'https://upload.wikimedia.org/wikipedia/commons/6/61/HTML5_logo_and_wordmark.svg',
  },
  CSS: {
    text: 'CSS3',
    color: 'white',
    link: 'https://developer.mozilla.org/en-US/docs/Web/CSS',
    icon: <FaCss3Alt />,
    image: 'https://upload.wikimedia.org/wikipedia/commons/d/d5/CSS3_logo_and_wordmark.svg',
  },
  Stripe: {
    text: 'Stripe',
    color: 'white',
    link: 'https://stripe.com/',
    icon: <SiStripe />,
    image: 'https://stripe.com/img/v3/newsroom/social.png',
  },
  JWT: {
    text: 'JWT (JSON Web Tokens)',
    color: 'white',
    link: 'https://jwt.io/',
    icon: <SiJsonwebtokens />,
    image: 'https://jwt.io/img/pic_logo.svg',
  },
  SocketIO: {
    text: 'Socket.IO',
    color: 'white',
    link: 'https://socket.io/',
    icon: <SiSocketdotio />,
    image: 'https://socket.io/images/logo.svg',
  },
  Express: {
    text: 'Express.js',
    color: 'white',
    link: 'https://expressjs.com/',
    icon: <SiExpress />,
    image: 'https://upload.wikimedia.org/wikipedia/commons/6/64/Expressjs.png',
  },
  Git: {
    text: 'Git',
    color: 'white',
    link: 'https://git-scm.com/',
    icon: <FaGit />,
    image: 'https://git-scm.com/images/logos/downloads/Git-Icon-1788C.png',
  },
  Linux: {
    text: 'Linux',
    color: 'white',
    link: 'https://www.linux.org/',
    icon: <FaLinux />,
    image: 'https://upload.wikimedia.org/wikipedia/commons/a/af/Tux.png',
  },
  Vite: {
    text: 'Vite',
    color: 'white',
    link: 'https://vitejs.dev/',
    icon: <SiVite />,
    image: 'https://vitejs.dev/logo.svg',
  },
  Mysql: {
    text: 'MySQL',
    color: 'white',
    link: 'https://www.mysql.com/',
    icon: <SiMysql />,
    image: 'https://upload.wikimedia.org/wikipedia/en/d/dd/MySQL_logo.svg',
  },
  Redux: {
    text: 'Redux',
    color: 'white',
    link: 'https://redux.js.org/',
    icon: <SiRedux />,
    image: 'https://redux.js.org/img/redux-logo-landscape.png',
  },
  Razorpay: {
    text: 'Razorpay',
    color: 'white',
    link: 'https://razorpay.com/',
    icon: <SiRazorpay />,
    image: 'https://razorpay.com/assets/razorpay.svg',
  },
};
