import { ReactOriginal, NodejsOriginal, JavascriptPlain, TypescriptOriginal, PostmanOriginal } from 'devicons-react';

import {
  SiD3Dotjs,
  SiEjs,
  SiFastapi,
  SiTensorflow,
  SiEthereum,
  SiPolygon,
  SiStreamlit,
  SiGraphql,
  SiCplusplus,
  SiPrisma,
  SiPython,
  SiScikitlearn,
  SiPandas, SiNumpy,
  SiPytorch,
  SiMlflow,
  SiSocketdotio,
  SiPrometheus,
  SiGrafana,
  SiApachehadoop
} from 'react-icons/si';

import { FaBrain } from 'react-icons/fa';  // For GenAI (using brain icon)
import { GiFactory } from 'react-icons/gi'; // Placeholder for Apache Mahout

import {
  FaAws,
  FaBootstrap,
  FaDocker,
  FaGitlab,
  FaGithub,
  FaCss3Alt,
  FaHtml5
} from 'react-icons/fa';

import { FaGit, FaLinux } from 'react-icons/fa';
import { SiExpress, SiVite, SiMysql } from 'react-icons/si';

import {
  SiKubernetes,
  SiRedis,
  SiPostgresql,
  SiFirebase,
  SiMongodb,
  SiTailwindcss,
  SiStripe,
  SiJsonwebtokens,
  SiRedux,
  SiRazorpay,
} from 'react-icons/si';

import { MdSpeed } from 'react-icons/md'; // Performance icon

export const tags = {
  React: {
    text: 'React',
    color: 'white',
    link: 'https://reactjs.org/',
    icon: <ReactOriginal />,
    image: 'https://i0.wp.com/css-tricks.com/wp-content/uploads/2018/04/react.jpg?fit=1200%2C600&ssl=1',
  },
  'Node.js': {
    text: 'Node.js',
    color: 'white',
    link: 'https://nodejs.org/',
    icon: <NodejsOriginal />,
    image: 'https://jobtech.jp/wp-content/uploads/node.png',
  },
  JavaScript: {
    text: 'JavaScript',
    color: 'white',
    link: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript',
    icon: <JavascriptPlain color='#F7DF1E'/>,
    image: 'https://www.keycdn.com/img/support/javascript.png',
  },
  TypeScript: {
    text: 'TypeScript',
    color: 'white',
    link: 'https://www.typescriptlang.org/',
    icon: <TypescriptOriginal />,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Typescript.svg/640px-Typescript.svg.png',
  },
  Docker: {
    text: 'Docker',
    color: 'white',
    link: 'https://www.docker.com/',
    icon: <FaDocker color="#2496ED"/>,
    image: 'https://www.opc-router.de/wp-content/uploads/2023/07/Docker_150x150px-01-01-01.png',
  },
  Pandas: {
    text: 'Pandas',
    color: 'white',
    link: 'https://pandas.pydata.org/',
    icon: <SiPandas color="#150458" />,  // Pandas dark blue
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSdWEAnQYTiT_XzgM-7Hrt2g2p4Pe_ZNvD7WMiviHIds4XAFLPqsGxdjX-Px07E3AopDsU',
  },
  NumPy: {
    text: 'NumPy',
    color: 'white',
    link: 'https://numpy.org/',
    icon: <SiNumpy color="#013243" />,  // NumPy dark teal
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8GOwYelkyRCn5rHGSAJhRitef065G1EAVYFSDPzsbAeELyLSPmb8ibluWr_Bn54MciGI',
  },
  D3js: {
    text: 'D3.js',
    color: 'white',
    link: 'https://d3js.org/',
    icon: <SiD3Dotjs />,
    image: 'https://d3js.org/logo.svg',
  },
  EJS: {
    text: 'EJS',
    color: 'white',
    link: 'https://ejs.co/',
    icon: <SiEjs color='#000000'/>,
    image: 'https://play-lh.googleusercontent.com/xCP_MYHEbU6Z8r5AieE_GczkWeH1-jTk5jVKC2qx7Z5PAgKLUrAcSsMfOF0BqwlZv_hc',
  },
  Hadoop: {
    text: 'Hadoop',
    color: 'white',
    link: 'https://hadoop.apache.org/',
    icon: <SiApachehadoop color="#66CCFF"/>,
    image: 'https://miro.medium.com/v2/resize:fit:1400/1*aFPoPQSaO4DFD7ezZC8WrQ.png',
  },
  ApacheMahout: {
    text: 'Apache Mahout',
    color: 'white',
    link: 'https://mahout.apache.org/',
    icon: <GiFactory />,
    image: 'https://mahout.apache.org/images/mahout_logo.png',
  },
  FastAPI: {
    text: 'FastAPI',
    color: 'white',
    link: 'https://fastapi.tiangolo.com/',
    icon: <SiFastapi color='#009688'/>,
    image: 'https://res.cloudinary.com/harendra21/image/upload/v1742473055/withcodeexample.com/getting-started-with-python-fastapi-a-comprehensive-guide_tnigh2.jpg',
  },
  TensorFlow: {
    text: 'TensorFlow',
    color: 'white',
    link: 'https://www.tensorflow.org/',
    icon: <SiTensorflow color='#FF6F00'/>,
    image: 'https://cdn-1.webcatalog.io/catalog/tensorflow/tensorflow-social-preview.png?v=1714783080859',
  },
  Ethereum: {
    text: 'Ethereum',
    color: 'white',
    link: 'https://ethereum.org/',
    icon: <SiEthereum />,
    image: 'https://ethereum.org/static/6a436922b38e650d74bb8238c33b8a52/6a435/eth-diamond-black.png',
  },
  Polygon: {
    text: 'Polygon',
    color: 'white',
    link: 'https://polygon.technology/',
    icon: <SiPolygon />,
    image: 'https://polygon.technology/media-kit/matic-token-icon.svg',
  },
  Streamlit: {
    text: 'Streamlit',
    color: 'white',
    link: 'https://streamlit.io/',
    icon: <SiStreamlit color="#FF4B4B"/>,
    image: 'https://images.seeklogo.com/logo-png/44/1/streamlit-logo-png_seeklogo-441815.png',
  },
  GraphQL: {
    text: 'GraphQL',
    color: 'white',
    link: 'https://graphql.org/',
    icon: <SiGraphql color="#E10098"/>,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4QUI4jglBf_evVJIZTfPAh_Av6MzdfrVrdA&s',
  },
  GenAI: {
    text: 'Generative AI',
    color: 'white',
    link: 'https://en.wikipedia.org/wiki/Generative_artificial_intelligence',
    icon: <FaBrain color='#000000'/>,
    image: 'https://www.docker.com/app/uploads/2024/04/1300x1300_GenAi.png',
  },
  PostgreSQL: {
    text: 'PostgreSQL',
    color: 'white',
    link: 'https://www.postgresql.org/',
    icon: <SiPostgresql color='#336791'/>,
    image: 'https://images.ctfassets.net/6yom6slo28h2/fJUJrqHAzWweaJZvNXgWS/446631a4e2f0cc825292c982c12e173a/postgresql.jpg?w=500&h=324&fl=progressive&q=100&fm=jpg',
  },
  Prisma: {
    text: 'Prisma',
    color: 'white',
    link: 'https://www.prisma.io/',
    icon: <SiPrisma color="#2D3748"/>,
    image: 'https://www.datocms-assets.com/58377/1688031395-logo_on_light.svg',
  },
  WebSocket: {
    text: 'WebSocket',
    color: 'white',
    link: 'https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API',
    icon: <SiSocketdotio color='#000000'/>,
    image: 'https://s3.amazonaws.com/kinlane-productions2/talks/api-days-paris-2018/api-not-rest-14.png',
  },
  PyTorch: {
    text: 'PyTorch',
    color: 'white',
    link: 'https://pytorch.org/',
    icon: <SiPytorch color="#EE4C2C" />,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRoBwo70v-oZ0qGHyoUni1RLYCWg4REUz7znw&s',
  },
  Python: {
    text: 'Python',
    color: 'white',
    link: 'https://www.python.org/',
    icon: <SiPython color='#3776AB'/>,
    image: 'https://niltechedu.com/blog/wp-content/uploads/2021/11/python-programming-language.png',
  },
  ScikitLearn: {
    text: 'Scikit-learn',
    color: 'white',
    link: 'https://scikit-learn.org/',
    icon: <SiScikitlearn color='#F7931E'/>,
    image: 'https://image.spreadshirtmedia.com/image-server/v1/compositions/T127A1PA4192PT21X6Y11D1047062111W2105H1134/views/1,width=650,height=650,appearanceId=1,backgroundColor=ffffff.jpg',
  },
  MLflow: {
    text: 'MLflow',
    color: 'white',
    link: 'https://mlflow.org/',
    icon: <SiMlflow />,
    image: 'https://mlflow.org/docs/latest/_static/mlflow-logo.png',
  },
  Prometheus: {
    text: 'Prometheus',
    color: 'white',
    link: 'https://prometheus.io/',
    icon: <SiPrometheus />,
    image: 'https://prometheus.io/assets/prometheus_logo_grey.png',
  },
  Grafana: {
    text: 'Grafana',
    color: 'white',
    link: 'https://grafana.com/',
    icon: <SiGrafana />,
    image: 'https://grafana.com/static/img/grafana_icon.svg',
  },
  Postman: {
    text: 'Postman',
    color: 'white',
    link: 'https://www.postman.com/',
    icon: <PostmanOriginal />,
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCXV1eqV2Jhujkym1X5XBqcRaonE9gnWBQ-w&s',
  },
  GitLab: {
    text: 'GitLab',
    color: 'white',
    link: 'https://gitlab.com/',
    icon: <FaGitlab color='#F05032' />,
    image: 'https://about.gitlab.com/images/press/logo/png/gitlab-logo-gray-stacked-rgb.png',
  },
  GitHub: {
    text: 'GitHub',
    color: 'white',
    link: 'https://github.com/',
    icon: <FaGithub color='#000000'/>,
    image: 'https://static.vecteezy.com/system/resources/previews/016/833/872/non_2x/github-logo-git-hub-icon-on-white-background-free-vector.jpg',
  },
  Cpp:{
    text: 'Cpp',
    color: 'white',
    link: 'https://en.wikipedia.org/wiki/C%2B%2B',
    icon: <SiCplusplus color='#00599C'/>,
    image: 'https://images.prismic.io/keep-it/cbe401fa-ce4b-4644-985f-e2bb42b909ef_28_WhyC%2B%2B.png?auto=compress,format&rect=0,0,1200,1200&w=800&h=800',
  },
  Bootstrap: {
    text: 'Bootstrap',
    color: 'white',
    link: 'https://getbootstrap.com/',
    icon: <FaBootstrap color='#7952B3'/>,
    image: 'https://logowik.com/content/uploads/images/bootstrap-new725.logowik.com.webp',
  },
  AWS: {
    text: 'AWS',
    color: 'white',
    link: 'https://aws.amazon.com/',
    icon: <FaAws color="#FF9900"/>,
    image: 'https://a0.awsstatic.com/libra-css/images/logos/aws_logo_smile_1200x630.png',
  },
  'CI/CD': {
    text: 'CI/CD',
    color: 'white',
    link: 'https://en.wikipedia.org/wiki/CI/CD',
    icon: <FaGitlab />,
    image: 'https://cdn-icons-png.flaticon.com/512/3509/3509412.png',
  },
  Kubernetes: {
    text: 'Kubernetes',
    color: 'white',
    link: 'https://kubernetes.io/',
    icon: <SiKubernetes />,
    image: 'https://upload.wikimedia.org/wikipedia/commons/3/39/Kubernetes_logo_without_workmark.svg',
  },
  Redis: {
    text: 'Redis',
    color: 'white',
    link: 'https://redis.io/',
    icon: <SiRedis color='#DC382D'/>,
    image: 'https://redis.io/images/redis-white.png',
  },
  Firebase: {
    text: 'Firebase',
    color: 'white',
    link: 'https://firebase.google.com/',
    icon: <SiFirebase color='#FFCA28'/>,
    image: 'https://firebase.google.com/downloads/brand-guidelines/PNG/logo-standard.png',
  },
  Mongo: {
    text: 'MongoDB',
    color: 'white',
    link: 'https://www.mongodb.com/',
    icon: <SiMongodb color='#47A248'/>,
    image: 'https://images.seeklogo.com/logo-png/48/1/mongodb-logo-png_seeklogo-481256.png',
  },
  Tailwindcss: {
    text: 'Tailwind CSS',
    color: 'white',
    link: 'https://tailwindcss.com/',
    icon: <SiTailwindcss color='#06B6D4'/>,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTSDKn3vA2YUbXzN0ZC3gALWJ08gJN-Drl15w&s',
  },
  Performance: {
    text: 'Performance Optimization',
    color: 'white',
    link: 'https://web.dev/performance-scoring/',
    icon: <MdSpeed />,
    image: 'https://upload.wikimedia.org/wikipedia/commons/e/e8/Speedometer_icon.svg',
  },
  HTML: {
    text: 'HTML5',
    color: 'white',
    link: 'https://developer.mozilla.org/en-US/docs/Web/HTML',
    icon: <FaHtml5 color="#E34F26" />,
    image: 'https://cdn.pixabay.com/photo/2018/05/08/21/28/html5-3384014_1280.png',
  },
  CSS: {
    text: 'CSS3',
    color: 'white',
    link: 'https://developer.mozilla.org/en-US/docs/Web/CSS',
    icon: <FaCss3Alt color="#1572B6"/>,
    image: 'https://cdn.dribbble.com/users/66221/screenshots/1655604/css3.png',
  },
  Stripe: {
    text: 'Stripe',
    color: 'white',
    link: 'https://stripe.com/',
    icon: <SiStripe color="#635BFF"/>,
    image: 'https://images.ctfassets.net/kftzwdyauwt9/6c20363e-30c0-486d-2e9bfa611583/b15f2e43a5a525763c966ab4562a31b2/stripe.jpg?w=3840&q=90&fm=webp',
  },
  JWT: {
    text: 'JWT',
    color: 'white',
    link: 'https://jwt.io/',
    icon: <SiJsonwebtokens color='#000000'/>,
    image: 'https://miro.medium.com/v2/resize:fit:800/1*i8N6u2G7l_SaOB1O2tPgIw.png',
  },
  SocketIO: {
    text: 'Socket.IO',
    color: 'white',
    link: 'https://socket.io/',
    icon: <SiSocketdotio />,
    image: 'https://socket.io/images/logo.svg',
  },
  Express: {
    text: 'Express',
    color: 'white',
    link: 'https://expressjs.com/',
    icon: <SiExpress color='#000000'/>,
    image: 'https://images.seeklogo.com/logo-png/33/1/express-js-logo-png_seeklogo-339850.png',
  },
  Git: {
    text: 'Git',
    color: 'white',
    link: 'https://git-scm.com/',
    icon: <FaGit color='#F05032'/>,
    image: 'https://blogbyte.in/media/blog/2025/git.png',
  },
  Linux: {
    text: 'Linux',
    color: 'white',
    link: 'https://www.linux.org/',
    icon: <FaLinux color='#000000'/>,
    image: 'https://miro.medium.com/v2/resize:fit:1400/0*Qqqd7UsfFDPL7WXh.jpeg',
  },
  Vite: {
    text: 'Vite',
    color: 'white',
    link: 'https://vitejs.dev/',
    icon: <SiVite color='#646CFF'/>,
    image: 'https://miro.medium.com/v2/resize:fit:1200/1*U78E_19tuLCWwzYX9JNAdg.png',
  },
  Mysql: {
    text: 'MySQL',
    color: 'white',
    link: 'https://www.mysql.com/',
    icon: <SiMysql color='#4479A1'/>,
    image: 'https://logowik.com/content/uploads/images/mysql.jpg',
  },
  Redux: {
    text: 'Redux',
    color: 'white',
    link: 'https://redux.js.org/',
    icon: <SiRedux color='#764ABC'/>,
    image: 'https://miro.medium.com/v2/resize:fit:1115/1*GiVzBKR6JFYrSq-6kf8F2A.png',
  },
  Razorpay: {
    text: 'Razorpay',
    color: 'white',
    link: 'https://razorpay.com/',
    icon: <SiRazorpay color="#0B5FFF"/>,
    image: 'https://medusajs.com/images/plugin-icons/medusa-payment-razorpay-icon.svg',
  },
};
